name: Deploy to GitHub Pages

on:
  # Déclencher le workflow à chaque push sur la branche main
  push:
    branches: [ main ]
  # Permet de lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

# Autoriser ce job à cloner le dépôt et créer un déploiement GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Définir un seul déploiement concurrent
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
